In [1]:
import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols

In [2]:
df = pd.read_csv('One way anova.csv')
df.head()

   CWP  Responses
0   15          7
1   15          7
2   15         15
3   15         11
4   15          9

In [3]:
mod = ols('Responses~C(CWP)', data=df).fit()

In [4]:
aova = sm.stats.anova_lm(mod, typ=2)

In [5]:
aova

          sum_sq    df          F    PR(>F)
C(CWP)    475.76   4.0  14.756824  0.000009
Residual  161.20  20.0        NaN       NaN

In [6]:
df = pd.read_csv('Question 2 anova.csv')
df.head()

   temp  cc  responses
0    50  40         17
1    50  40         20
2    50  60         16
3    50  60         21
4    50  80         24

In [7]:
mod2 = ols('responses~C(temp)+C(cc)+C(temp)*C(cc)', data=df).fit()

In [8]:
aova2 = sm.stats.anova_lm(mod2, typ=2)

In [9]:
aova2

                  sum_sq    df          F        PR(>F)
C(temp)        156.09375   3.0   7.672811  2.126631e-03
C(cc)          698.34375   3.0  34.327189  3.349763e-07
C(temp):C(cc)  113.78125   9.0   1.864311  1.327481e-01
Residual       108.50000  16.0        NaN           NaN

In [10]:
df = pd.read_csv('Question 3 anova.csv')
df.head(2)

   Temp  Density  Salinity  Responses
0    25       80        10         86
1    25       80        10         52

In [11]:
mod3 = ols('Responses~C(Temp)+C(Density)+C(Salinity)+C(Temp)*C(Density)*C(Salinity)', data=df).fit()

In [12]:
aova3 = sm.stats.anova_lm(mod3, typ=2)

In [13]:
aova3

                                       sum_sq    df          F        PR(>F)
C(Temp)                          15376.000000   1.0   5.295171  3.037608e-02
C(Density)                       21218.777778   1.0   7.307301  1.241519e-02
C(Salinity)                      96762.500000   2.0  16.661485  2.901287e-05
C(Temp):C(Density)                8711.111111   1.0   2.999923  9.610391e-02
C(Temp):C(Salinity)             300855.166667   2.0  51.804096  1.958810e-09
C(Density):C(Salinity)             674.388889   2.0   0.116123  8.908632e-01
C(Temp):C(Density):C(Salinity)   24038.388889   2.0   4.139158  2.854990e-02
Residual                         69690.666667  24.0        NaN           NaN