In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day48-simple-linear-regression/placement.csv")

In [3]:
df

     cgpa  package
0    6.89     3.26
1    5.12     1.98
2    7.82     3.25
3    7.42     3.67
4    6.94     3.57
..    ...      ...
195  6.93     2.46
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33

[200 rows x 2 columns]

In [4]:
x = df.iloc[:,0:1]
y = df.iloc[:,-1]

In [5]:
x

     cgpa
0    6.89
1    5.12
2    7.82
3    7.42
4    6.94
..    ...
195  6.93
196  5.89
197  7.21
198  7.63
199  6.22

[200 rows x 1 columns]

In [6]:
y

0      3.26
1      1.98
2      3.25
3      3.67
4      3.57
       ...
195    2.46
196    2.57
197    3.24
198    3.96
199    2.33
Name: package, Length: 200, dtype: float64

In [30]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [31]:
from sklearn.linear_model import LinearRegression

In [32]:
lr = LinearRegression()

In [33]:
lr.fit(x_train,y_train)

LinearRegression()

In [34]:
x_test

     cgpa
18   6.94
170  6.22
107  6.33
98   7.69
177  7.09
182  5.88
5    7.89
146  6.07
12   8.94
152  7.37
61   5.48
125  7.33
180  6.19
154  7.08
80   7.63
7    6.75
33   6.35
130  6.68
37   5.90
74   6.85
183  7.28
145  5.84
45   7.87
159  8.71
60   5.61
123  5.10
179  7.14
185  6.31
122  5.12
44   5.09
16   6.84
55   8.20
150  6.30
111  5.42
22   6.14
189  8.11
129  7.29
4    6.94
83   8.44
106  6.13

In [24]:
y_test

112    4.10
29     3.49
182    2.08
199    2.33
193    1.94
85     1.48
10     1.86
54     3.09
115    4.21
35     2.87
12     3.65
92     4.00
13     2.89
126    2.60
174    2.99
2      3.25
44     1.86
3      3.67
113    2.37
14     3.42
23     2.48
25     3.65
6      2.60
134    2.83
165    4.08
173    2.56
45     3.58
65     3.81
48     4.09
122    2.01
178    3.63
64     2.92
9      3.51
57     1.94
78     2.21
71     3.34
128    3.34
176    3.23
131    2.01
53     2.61
Name: package, dtype: float64

In [29]:
lr.predict([[8.58]])

C:\Users\BIPLAB\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([3.89111601])

In [27]:
lr.coef_

array([0.55795197])

In [28]:
lr.intercept_

-0.8961119222429144

In [39]:
y_pred=lr.predict(x_test)

In [40]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
print('mae', mean_absolute_error(y_test,y_pred))
print('mse', mean_squared_error(y_test,y_pred))
print('r2 score', r2_score(y_test,y_pred))

mae 0.2552433448620408
mse 0.10221131059334207
r2 score 0.7297167943957027