In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
train_df=pd.read_csv('IITG-train.csv')

In [3]:
train_df.sample(10)

,id,title,Rating,maincateg,platform,price1,actprice1,Offer %,norating1,noreviews1,star_5f,star_4f,star_3f,star_2f,star_1f,fulfilled1
2677,7574,Men's Lace up Walking Shoes Running Shoes Ligh...,3.7,Men,Flipkart,359,999,64.06%,169.0,15.0,80.0,22.0,24.0,18,25,0
11626,13211,Fashionable Durable Breathable Running shoes f...,4.2,Men,Flipkart,369,999,63.06%,1134.0,152.0,703.0,191.0,93.0,63,84,0
14794,3146,Women Pink Heels Sandal,3.8,Women,Flipkart,599,899,33.37%,243.0,28.0,105.0,62.0,28.0,23,25,1
6539,16017,Flip Flops,4.0,Women,Flipkart,499,899,44.49%,299.0,36.0,150.0,65.0,42.0,16,26,1
9843,2076,CatBird Women's Loafers,4.0,Women,Amazon,497,499,0.40%,228.0,116.0,11.0,5.0,9.0,21,54,0
1672,10674,Revolution 4 Running Shoes For Men (Grey),4.3,Men,Flipkart,2587,3695,29.99%,38546.0,5161.0,22408.0,9475.0,3182.0,1117,2364,1
6112,16259,Slippers,4.3,Men,Flipkart,1799,2999,40.01%,8.0,2.0,6.0,0.0,1.0,0,1,1
5663,1607,Men's Juit & Mojari | Faux leather juti | Moja...,4.0,Men,Flipkart,499,1199,58.38%,257.0,26.0,136.0,47.0,30.0,17,27,0
652,1228,Women Black Heels Sandal,4.3,Women,Flipkart,474,999,52.55%,255.0,51.0,167.0,39.0,18.0,10,21,0
12723,16923,Slides,4.0,Men,Flipkart,242,999,75.78%,832.0,77.0,486.0,122.0,74.0,51,99,0

In [4]:
train_df.set_index('id',inplace=True)

In [5]:
train_df

,title,Rating,maincateg,platform,price1,actprice1,Offer %,norating1,noreviews1,star_5f,star_4f,star_3f,star_2f,star_1f,fulfilled1
id,,,,,,,,,,,,,,,
16695,Fashionable & Comfortable Bellies For Women (...,3.9,Women,Flipkart,698,999,30.13%,38.0,7.0,17.0,9.0,6.0,3,3,0
5120,Combo Pack of 4 Casual Shoes Sneakers For Men ...,3.8,Men,Flipkart,999,1999,50.03%,531.0,69.0,264.0,92.0,73.0,29,73,1
18391,Cilia Mode Leo Sneakers For Women (White),4.4,Women,Flipkart,2749,4999,45.01%,17.0,4.0,11.0,3.0,2.0,1,0,1
495,Men Black Sports Sandal,4.2,Men,Flipkart,518,724,15.85%,46413.0,6229.0,1045.0,12416.0,5352.0,701,4595,1
16408,Men Green Sports Sandal,3.9,Men,Flipkart,1379,2299,40.02%,77.0,3.0,35.0,21.0,7.0,7,7,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16554,Women Maroon Heels Sandal,4.3,Women,Flipkart,567,1199,52.71%,807.0,114.0,485.0,177.0,61.0,41,43,0
19600,Women Multicolor Flats Sandal,3.9,Women,Flipkart,499,998,50.00%,246.0,34.0,120.0,45.0,37.0,16,28,1
6733,Women Navy Flats Sandal,3.7,Women,Flipkart,329,499,34.07%,NaN,18.0,NaN,NaN,20.0,10,15,1
3889,Red Chief Men's Sneakers,3.9,Men,Amazon,2249,4499,50.01%,750.0,479.0,13.0,6.0,10.0,25,47,1
13682,Slip On For Men (Brown),5.0,Men,Flipkart,1539,2799,45.02%,8.0,1.0,8.0,0.0,0.0,0,0,1

In [6]:
train_df['maincateg'].mode()

0    Women
Name: maincateg, dtype: object

In [7]:
train_df['maincateg'].fillna('Women', inplace=True)

In [8]:
train_df['median_norating1']=train_df['norating1'].fillna(train_df['norating1'].median())
train_df['median_noreviews1']=train_df['noreviews1'].fillna(train_df['noreviews1'].median())
train_df['median_star_5f']=train_df['star_5f'].fillna(train_df['star_5f'].median())

In [9]:
train_df['median_star_4f']=train_df['star_4f'].fillna(train_df['star_4f'].median())

In [10]:
train_df['median_star_3f']=train_df['star_3f'].fillna(train_df['star_3f'].median())

In [11]:
train_df.columns

Index(['title', 'Rating', 'maincateg', 'platform', 'price1', 'actprice1',
       'Offer %', 'norating1', 'noreviews1', 'star_5f', 'star_4f', 'star_3f',
       'star_2f', 'star_1f', 'fulfilled1', 'median_norating1',
       'median_noreviews1', 'median_star_5f', 'median_star_4f',
       'median_star_3f'],
      dtype='object')

In [12]:
train_df=train_df[['title', 'Rating', 'maincateg', 'platform',  'actprice1','Offer %','median_norating1','median_noreviews1','median_star_5f','median_star_4f','median_star_3f','star_2f', 'star_1f','price1']]

In [13]:
train_df.isnull().sum()

title                0
Rating               0
maincateg            0
platform             0
actprice1            0
Offer %              0
median_norating1     0
median_noreviews1    0
median_star_5f       0
median_star_4f       0
median_star_3f       0
star_2f              0
star_1f              0
price1               0
dtype: int64

In [14]:
col=['title', 'Rating', 'gender', 'platform', 'act_price',
       'Offer_%', 'rating_counts', 'reviews_counts', '5_star', '4_star', '3_star',
       '2_star', '1_star','dis_price']

In [15]:
train_df.columns=col

In [16]:
train_df

,title,Rating,gender,platform,act_price,Offer_%,rating_counts,reviews_counts,5_star,4_star,3_star,2_star,1_star,dis_price
id,,,,,,,,,,,,,,
16695,Fashionable & Comfortable Bellies For Women (...,3.9,Women,Flipkart,999,30.13%,38.0,7.0,17.0,9.0,6.0,3,3,698
5120,Combo Pack of 4 Casual Shoes Sneakers For Men ...,3.8,Men,Flipkart,1999,50.03%,531.0,69.0,264.0,92.0,73.0,29,73,999
18391,Cilia Mode Leo Sneakers For Women (White),4.4,Women,Flipkart,4999,45.01%,17.0,4.0,11.0,3.0,2.0,1,0,2749
495,Men Black Sports Sandal,4.2,Men,Flipkart,724,15.85%,46413.0,6229.0,1045.0,12416.0,5352.0,701,4595,518
16408,Men Green Sports Sandal,3.9,Men,Flipkart,2299,40.02%,77.0,3.0,35.0,21.0,7.0,7,7,1379
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16554,Women Maroon Heels Sandal,4.3,Women,Flipkart,1199,52.71%,807.0,114.0,485.0,177.0,61.0,41,43,567
19600,Women Multicolor Flats Sandal,3.9,Women,Flipkart,998,50.00%,246.0,34.0,120.0,45.0,37.0,16,28,499
6733,Women Navy Flats Sandal,3.7,Women,Flipkart,499,34.07%,308.0,18.0,150.0,60.0,20.0,10,15,329
3889,Red Chief Men's Sneakers,3.9,Men,Amazon,4499,50.01%,750.0,479.0,13.0,6.0,10.0,25,47,2249
13682,Slip On For Men (Brown),5.0,Men,Flipkart,2799,45.02%,8.0,1.0,8.0,0.0,0.0,0,0,1539

In [17]:
train_df=train_df.drop(columns=['title','reviews_counts','rating_counts','Offer_%'],axis=1)

In [18]:
train_df

,Rating,gender,platform,act_price,5_star,4_star,3_star,2_star,1_star,dis_price
id,,,,,,,,,,
16695,3.9,Women,Flipkart,999,17.0,9.0,6.0,3,3,698
5120,3.8,Men,Flipkart,1999,264.0,92.0,73.0,29,73,999
18391,4.4,Women,Flipkart,4999,11.0,3.0,2.0,1,0,2749
495,4.2,Men,Flipkart,724,1045.0,12416.0,5352.0,701,4595,518
16408,3.9,Men,Flipkart,2299,35.0,21.0,7.0,7,7,1379
...,...,...,...,...,...,...,...,...,...,...
16554,4.3,Women,Flipkart,1199,485.0,177.0,61.0,41,43,567
19600,3.9,Women,Flipkart,998,120.0,45.0,37.0,16,28,499
6733,3.7,Women,Flipkart,499,150.0,60.0,20.0,10,15,329
3889,3.9,Men,Amazon,4499,13.0,6.0,10.0,25,47,2249
13682,5.0,Men,Flipkart,2799,8.0,0.0,0.0,0,0,1539

In [19]:
train_df['gender'].replace({'Men':0,'Women':1},inplace=True)

In [20]:
train_df['platform'].replace({'Amazon':0,'Flipkart':1},inplace=True)

In [21]:
train_df

,Rating,gender,platform,act_price,5_star,4_star,3_star,2_star,1_star,dis_price
id,,,,,,,,,,
16695,3.9,1,1,999,17.0,9.0,6.0,3,3,698
5120,3.8,0,1,1999,264.0,92.0,73.0,29,73,999
18391,4.4,1,1,4999,11.0,3.0,2.0,1,0,2749
495,4.2,0,1,724,1045.0,12416.0,5352.0,701,4595,518
16408,3.9,0,1,2299,35.0,21.0,7.0,7,7,1379
...,...,...,...,...,...,...,...,...,...,...
16554,4.3,1,1,1199,485.0,177.0,61.0,41,43,567
19600,3.9,1,1,998,120.0,45.0,37.0,16,28,499
6733,3.7,1,1,499,150.0,60.0,20.0,10,15,329
3889,3.9,0,0,4499,13.0,6.0,10.0,25,47,2249
13682,5.0,0,1,2799,8.0,0.0,0.0,0,0,1539

In [22]:
x=train_df.drop('dis_price',axis=1)
y=train_df['dis_price'].values
y=y.reshape(-1,1)

In [23]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(x)

MinMaxScaler()

In [24]:
x_scaled=scaler.transform(x)

In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,test_size=0.25,random_state=0)
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [26]:
lr.fit(x_train,y_train)

LinearRegression()

In [27]:
y_pred=lr.predict(x_test)
y_pred

array([[496.826944  ],
       [733.03664554],
       [298.07168226],
       ...,
       [449.85712313],
       [385.10960859],
       [244.88407696]])

In [28]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.810585023203036

In [29]:
test_df=pd.read_csv('IITG-test (1).csv')

In [30]:
test_df

,id,title,Rating,maincateg,platform,actprice1,norating1,noreviews1,star_5f,star_4f,star_3f,star_2f,star_1f,fulfilled1
0,2242,Casuals For Men (Blue),3.8,Men,Flipkart,999,27928,3543,14238.0,4295,3457,1962,3976.0,1
1,20532,Women Black Flats Sandal,3.9,Women,Flipkart,499,3015,404,1458.0,657,397,182,321.0,1
2,10648,Women Gold Wedges Sandal,3.9,Women,Flipkart,999,449,52,229.0,70,71,33,46.0,1
3,20677,Men's Height Increasing High Heel Formal Party...,3.9,Men,Flipkart,2999,290,40,141.0,51,49,17,32.0,1
4,12593,Loafers For Men (Tan),3.9,Men,Flipkart,999,2423,326,1265.0,414,293,143,308.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5239,14033,Women Off White Flats Sandal,NaN,Women,Flipkart,699,1235,153,NaN,323,155,62,NaN,1
5240,297,Slip On For Men (Tan),3.9,Men,Flipkart,1993,329,56,350.0,37,60,5,37.0,0
5241,18733,Women Grey Heels Sandal,3.8,Women,Flipkart,999,1280,135,574.0,290,172,94,150.0,0
5242,6162,Womens Casual Comfort Stylish Black High Heel ...,3.9,Women,Flipkart,499,4867,574,2384.0,974,648,328,533.0,0
5243,13574,ZAPATOZ Women's Casual PU Leather Sneaker Shoes,3.9,Women,Amazon,749,8,5,28.0,0,0,0,72.0,1

In [31]:
test_df.set_index('id',inplace=True)

In [32]:
test_df['maincateg'].fillna('Women', inplace=True)

In [33]:
test_df['median_Rating']=test_df['Rating'].fillna(train_df['Rating'].median())
test_df['median_star_5f']=test_df['star_5f'].fillna(test_df['star_5f'].median())
test_df['median_star_1f']=test_df['star_1f'].fillna(test_df['star_1f'].median())

In [34]:
test_df.columns

Index(['title', 'Rating', 'maincateg', 'platform', 'actprice1', 'norating1',
       'noreviews1', 'star_5f', 'star_4f', 'star_3f', 'star_2f', 'star_1f',
       'fulfilled1', 'median_Rating', 'median_star_5f', 'median_star_1f'],
      dtype='object')

In [35]:
test_df=test_df[['title', 'median_Rating', 'maincateg', 'platform','actprice1','norating1','noreviews1','median_star_5f','star_4f','star_3f','star_2f', 'median_star_1f']]

In [36]:
col1=['title', 'Rating', 'gender', 'platform', 'act_price','rating_counts', 'reviews_counts', '5_star', '4_star', '3_star','2_star', '1_star']

In [37]:
test_df.columns=col1

In [38]:
test_df

,title,Rating,gender,platform,act_price,rating_counts,reviews_counts,5_star,4_star,3_star,2_star,1_star
id,,,,,,,,,,,,
2242,Casuals For Men (Blue),3.8,Men,Flipkart,999,27928,3543,14238.0,4295,3457,1962,3976.0
20532,Women Black Flats Sandal,3.9,Women,Flipkart,499,3015,404,1458.0,657,397,182,321.0
10648,Women Gold Wedges Sandal,3.9,Women,Flipkart,999,449,52,229.0,70,71,33,46.0
20677,Men's Height Increasing High Heel Formal Party...,3.9,Men,Flipkart,2999,290,40,141.0,51,49,17,32.0
12593,Loafers For Men (Tan),3.9,Men,Flipkart,999,2423,326,1265.0,414,293,143,308.0
...,...,...,...,...,...,...,...,...,...,...,...,...
14033,Women Off White Flats Sandal,4.0,Women,Flipkart,699,1235,153,156.0,323,155,62,29.0
297,Slip On For Men (Tan),3.9,Men,Flipkart,1993,329,56,350.0,37,60,5,37.0
18733,Women Grey Heels Sandal,3.8,Women,Flipkart,999,1280,135,574.0,290,172,94,150.0
6162,Womens Casual Comfort Stylish Black High Heel ...,3.9,Women,Flipkart,499,4867,574,2384.0,974,648,328,533.0
13574,ZAPATOZ Women's Casual PU Leather Sneaker Shoes,3.9,Women,Amazon,749,8,5,28.0,0,0,0,72.0

In [39]:
test_df=test_df.drop(columns=['title','reviews_counts','rating_counts'],axis=1)

In [40]:
test_df['gender'].replace({'Men':0,'Women':1},inplace=True)
test_df['platform'].replace({'Amazon':0,'Flipkart':1},inplace=True)

In [41]:
test_df_scaled=scaler.transform(test_df)

In [42]:
y_prediction=lr.predict(test_df_scaled)

In [43]:
y_prediction

array([[440.39789339],
       [262.55359248],
       [489.22991821],
       ...,
       [471.75999928],
       [254.38835748],
       [616.9465667 ]])

In [44]:
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor

from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score

In [45]:
ran=RandomForestRegressor(n_estimators=110,max_depth=40,random_state=0,criterion='squared_error')
ran.fit(x_train,y_train)
ran.score(x_test,y_test)

C:\Users\BIPLAB\AppData\Local\Temp\ipykernel_11628\3689672259.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  ran.fit(x_train,y_train)

0.9167194673376211

In [46]:
y_prediction1=ran.predict(test_df_scaled)
y_prediction1

array([426.45225108, 277.22998131, 435.50727273, ..., 392.6680573 ,
       206.90909091, 744.42727273])

In [47]:
bip1=pd.DataFrame(y_prediction1)

In [48]:
bip1.index = test_df.index

In [49]:
bip1.columns = ["price1"]

In [52]:
bip1.to_csv('predicted_offer_price4.csv')

In [53]:
biplab1=pd.read_csv('predicted_offer_price4.csv')